### ISSUE TITLE
Unsupported value: "rbac.authorization.k8s.io"

### ISSUE THREAD

**Issue by mamu-reply** [startxfr/helm-repository#10]
**Describe the bug**
When i try to install helm with a sa configuration in rbac it give me and apiGroup unsupported value.
The error is this:
RoleBinding.rbac.authorization.k8s.io "test-sa" is invalid: subjects[0].apiGroup: Unsupported value: "rbac.authorization.k8s.io": supported values: ""

**To Reproduce**
Install the helm package with this values:

**Expected behavior**
```
project:
    type: namespace
    name: mynamespace
rbac: 
  enabled: true
  groups: 
  - id: test
    name: test
    type: cluster
    role: view
  users: []
  sa:
  - id: test-sa
    name: test-sa
    role: admin

serviceAccounts:
  enabled: true
  list:
    - name: test-sa
```

I'm using this repo version:

  repository = "https://helm-repository.readthedocs.io/en/latest/packages/"
  version    = "11.28.129"
  chart      = "project"
