### ISSUE TITLE
cluster-rbac without group creation 

### ISSUE THREAD

**Issue by startxfr** [startxfr/helm-repository#17]
create boolean to enable or disable group creation. This will allow creation CRB without creating group because they will be automaticaly created by group sync on the auth provider side.

**Comment by startxfr** [comment]
done in release 14.6.31. 

Adding property `enableGroup` and `enableCRB` (default to true) for a group entry. 
Example of a **values.yaml** : 

```yaml
# Create groups if enabled
groups:
  # Enable the cluster groups creation
  enabled: false
  # List group to create
  list: 
  # Developper ID
  - id: mygroup
    # Developper name
    name: mygroup-example
    # Enable creation of the group (default true)
    enableGroup: true
    # Enable creation of the clusterroleBinding (default true)
    enableCRB: true
    # Developper cluster role
    role: basic-user
    # user enrolled in this group
    users: 
    - myuser-example
```
