### ISSUE TITLE
RFE: ability to add arbitrary labels/annotations to project/namespace in project helm chart

### ISSUE THREAD

**Issue by evgkrsk** [startxfr/helm-repository#9]
**Is your feature request related to a problem? Please describe.**
It is handy to create namespaces via "project" helm chart, but many k8s operators work with labels/annotations on namespaces. Chart doesn't provide any way to add such labels via values. Now we have to manually run "kubectl label ns..." for such cases :-(

**Describe the solution you'd like**
```yaml
project:
  type: namespace
  labels:
    goldilocks.fairwinds.com/enabled=true
    trivy-scan=true
    foo: bar
  annotations: {}
```

... translates in three labels on created namespace:
```yaml
labels:
  foo: bar
  goldilocks.fairwinds.com/enabled=true
  trivy-scan=true
```

... and similar for annotations.

**Describe alternatives you've considered**
Addition operator running just to label namespaces. Seems like terrible overkill.

**Comment by startxfr** [comment]
Hi @evgkrsk, I know that it's a long time, but better late than never, this feature is now implemented in release `14.6.21`
Example of a values.yaml file with additionnals labels.

```yaml
project: 
  enabled: true
  type: namespace
  name: myproject
  nodeSelector: "node-role.kubernetes.io/worker="
  additionalLabels: |
    mylabel: "myvalue"
  additionalAnnotations: |
    myannotation: "myvalue"
```
